// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUe66wzftqpTxywFhx14bkiWt_QYO3f44',
    appId: '1:144616307187:web:0910713d2bb3a2ea777a86',
    messagingSenderId: '144616307187',
    projectId: 'boite-a-livre-dc929',
    authDomain: 'boite-a-livre-dc929.firebaseapp.com',
    storageBucket: 'boite-a-livre-dc929.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClTIvHOOSS1H9WDDr81oXK_UdQD_CPvts',
    appId: '1:144616307187:android:f64e1a444df32e20777a86',
    messagingSenderId: '144616307187',
    projectId: 'boite-a-livre-dc929',
    storageBucket: 'boite-a-livre-dc929.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUe66wzftqpTxywFhx14bkiWt_QYO3f44',
    appId: '1:144616307187:ios:0910713d2bb3a2ea777a86',
    messagingSenderId: '144616307187',
    projectId: 'boite-a-livre-dc929',
    storageBucket: 'boite-a-livre-dc929.firebasestorage.app',
    iosClientId: '961144753286-7ok11g2s6jil8q414bsd28dju433qn7f.apps.googleusercontent.com',
    iosBundleId: 'com.antoineterrade.boite-a-livre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUe66wzftqpTxywFhx14bkiWt_QYO3f44',
    appId: '1:144616307187:ios:0910713d2bb3a2ea777a86',
    messagingSenderId: '144616307187',
    projectId: 'boite-a-livre-dc929',
    storageBucket: 'boite-a-livre-dc929.firebasestorage.app',
    iosClientId: '961144753286-7ok11g2s6jil8q414bsd28dju433qn7f.apps.googleusercontent.com',
    iosBundleId: 'com.antoineterrade.boite-a-livre',
  );
}
